const SET_CURRENT_FAVORITE_LIST = 'app/lists/SET_CURRENT_FAVORITE_LIST';
const UPDATE_CURRENT_FAVORITE_LIST_PRODUCTS =
  'app/lists/UPDATE_CURRENT_FAVORITE_LIST_PRODUCTS';
const UPDATE_CURRENT_PRODUCT = 'app/lists/UPDATE_CURRENT_PRODUCT';

export default {
  SET_CURRENT_FAVORITE_LIST,
  UPDATE_CURRENT_FAVORITE_LIST_PRODUCTS,

  UPDATE_CURRENT_PRODUCT,
};
