const UPDATE_USER = 'app/user/UPDATE_USER';
const UPDATE_TOKEN = 'app/user/UPDATE_TOKEN';

const UPDATE_IS_USER_MENU_OPEN = 'app/user/UPDATE_IS_USER_MENU_OPEN'

const UPDATE_IS_SIGN_IN_OPEN = 'app/user/UPDATE_IS_SIGN_IN_OPEN'
const UPDATE_IS_LOADING_SIGN_IN = 'app/user/IS_LOADING_SIGN_IN';
const UPDATE_IS_SUCCESS_SIGN_IN = 'app/user/IS_LOADING_SIGN_IN';
const START_SIGN_IN = 'app/user/START_SIGN_IN';
const SUCCESS_SIGN_IN = 'app/user/SUCCESS_SIGN_IN';
const FAILED_SIGN_IN = 'app/user/FAILED_SIGN_IN';

const UPDATE_IS_LOADING_FORGOT_PASSWORD = 'app/user/UPDATE_IS_LOADING_FORGOT_PASSWORD';
const UPDATE_IS_SUCCESS_FORGOT_PASSWORD = 'app/user/UPDATE_IS_SUCCESS_FORGOT_PASSWORD';
const START_FORGOT_PASSWORD = 'app/user/START_FORGOT_PASSWORD';
const SUCCESS_FORGOT_PASSWORD = 'app/user/SUCCESS_FORGOT_PASSWORD';
const FAILED_FORGOT_PASSWORD = 'app/user/FAILED_FORGOT_PASSWORD';
const START_CONFIRM_FORGOT_PASSWORD = 'app/user/START_CONFIRM_FORGOT_PASSWORD';
const CONFIRM_FORGOT_PASSWORD = 'app/user/CONFIRM_FORGOT_PASSWORD';

const UPDATE_IS_SIGN_UP_OPEN = 'app/user/UPDATE_IS_SIGN_UP_OPEN'
const UPDATE_IS_LOADING_SIGN_UP = 'app/user/IS_LOADING_SIGN_UP';
const UPDATE_IS_SUCCESS_SIGN_UP = 'app/user/IS_LOADING_SIGN_UP';
const START_SIGN_UP = 'app/user/START_SIGN_UP';
const SUCCESS_SIGN_UP = 'app/user/SUCCESS_SIGN_UP';
const FAILED_SIGN_UP = 'app/user/FAILED_SIGN_UP';
const START_CONFIRM_SIGN_UP = 'app/user/START_CONFIRM_SIGN_UP';
const CONFIRM_SIGN_UP = 'app/user/CONFIRM_SIGN_UP';

const UPDATE_FRIENDS = 'app/user/UPDATE_FRIENDS'
const UPDATE_OUTGOING_FRIEND_REQUESTS = 'app/user/UPDATE_OUTGOING_FRIEND_REQUESTS'
const UPDATE_INCOMING_FRIEND_REQUESTS = 'app/user/UPDATE_INCOMING_FRIEND_REQUESTS'
const UPDATE_IS_LOADING_FRIENDS = 'app/user/UPDATE_IS_LOADING_FRIENDS'
const UPDATE_SHOULD_REFRESH_FRIENDS = 'app/user/UPDATE_SHOULD_REFRESH_FRIENDS'

const UPDATE_IS_LOADING_SAVE_USER = 'app/user/UPDATE_IS_LOADING_SAVE_USER'

const REFRESH_SYNC = 'app/user/REFRESH_SYNC'

export default {
  UPDATE_USER,
  UPDATE_TOKEN,

  UPDATE_IS_USER_MENU_OPEN,

  UPDATE_IS_SIGN_IN_OPEN,
  UPDATE_IS_LOADING_SIGN_IN,
  UPDATE_IS_SUCCESS_SIGN_IN,
  START_SIGN_IN,
  SUCCESS_SIGN_IN,
  FAILED_SIGN_IN,

  UPDATE_IS_LOADING_FORGOT_PASSWORD,
  UPDATE_IS_SUCCESS_FORGOT_PASSWORD,
  START_FORGOT_PASSWORD,
  SUCCESS_FORGOT_PASSWORD,
  FAILED_FORGOT_PASSWORD,
  START_CONFIRM_FORGOT_PASSWORD,
  CONFIRM_FORGOT_PASSWORD,

  UPDATE_IS_SIGN_UP_OPEN,
  UPDATE_IS_LOADING_SIGN_UP,
  UPDATE_IS_SUCCESS_SIGN_UP,
  START_SIGN_UP,
  SUCCESS_SIGN_UP,
  FAILED_SIGN_UP,
  START_CONFIRM_SIGN_UP,
  CONFIRM_SIGN_UP,

  UPDATE_FRIENDS,
  UPDATE_OUTGOING_FRIEND_REQUESTS,
  UPDATE_INCOMING_FRIEND_REQUESTS,
  UPDATE_IS_LOADING_FRIENDS,
  UPDATE_SHOULD_REFRESH_FRIENDS,

  UPDATE_IS_LOADING_SAVE_USER,

  REFRESH_SYNC,
};
