const SET_IS_HOME_LOADING = 'app/product/SET_IS_HOME_LOADING';
const SET_HOME = 'app/product/SET_HOME';
const SET_HOME_WITHOUT_CATEGORIES = 'app/products/SET_HOME_WITHOUT_CATEGORIES';
const SET_HOME_ERROR = 'app/product/SET_HOME_ERROR';

const UPDATE_LAST_SEEN = 'app/product/UPDATE_LAST_SEEN';
const UPDATE_LAST_SEARCHED = 'app/product/UPDATE_LAST_SEARCHED';
const UPDATE_LAST_SCANNED = 'app/product/UPDATE_LAST_SCANNED';

const SET_SEARCH_QUERY = 'app/product/SET_SEARCH_QUERY';
const SET_SEARCH_RESULT = 'app/product/SET_SEARCH_RESULT';
const RESET_SEARCH = 'app/product/SET_SEARCH';
const SET_IS_SEARCH_LOADING = 'app/product/SET_IS_SEARCH_LOADING';
const SET_SEARCH_ERROR = 'app/product/SET_SEARCH_ERROR';

const SET_IS_LOADING_SEARCH_FILTERS =
  'app/product/SET_IS_LOADING_SEARCH_FILTERS';
const DO_UPDATE_SEARCH_FILTERS = 'app/product/DO_UPDATE_SEARCH_FILTERS';
const DO_UPDATE_ACTIVE_SEARCH_FILTERS =
  'app/product/DO_UPDATE_ACTIVE_SEARCH_FILTERS';

const SET_IS_SCANNING = 'app/product/SET_IS_SCANNING';
const SET_SCAN_PRODUCT = 'app/product/SET_SCAN_PRODUCT';
const SET_SCAN_ERROR = 'app/product/SET_SCAN_ERROR';

const SET_SHOW_PRODUCT_DETAILS = 'app/product/SET_SHOW_PRODUCT_DETAILS';
const SET_PRODUCT_POSITION = 'app/product/SET_PRODUCT_POSITION';

export default {
  SET_IS_HOME_LOADING,
  SET_HOME,
  SET_HOME_WITHOUT_CATEGORIES,
  SET_HOME_ERROR,

  UPDATE_LAST_SEEN,
  UPDATE_LAST_SEARCHED,
  UPDATE_LAST_SCANNED,

  // Search
  SET_SEARCH_QUERY,
  SET_SEARCH_RESULT,
  RESET_SEARCH,
  SET_IS_SEARCH_LOADING,
  SET_SEARCH_ERROR,

  SET_IS_LOADING_SEARCH_FILTERS,
  DO_UPDATE_SEARCH_FILTERS,
  DO_UPDATE_ACTIVE_SEARCH_FILTERS,

  SET_IS_SCANNING,
  SET_SCAN_PRODUCT,
  SET_SCAN_ERROR,

  SET_SHOW_PRODUCT_DETAILS,
  SET_PRODUCT_POSITION,
};
